# Generated by Django 5.2.17 on 2026-09-29 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoDeduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.SlugField(max_length=30, unique=True, verbose_name="código"),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "antes_de_pr",
                    models.BooleanField(
                        default=False, verbose_name="antes de la retención de PR"
                    ),
                ),
                (
                    "antes_de_federal",
                    models.BooleanField(
                        default=False, verbose_name="antes de la retención federal"
                    ),
                ),
                (
                    "antes_de_fica",
                    models.BooleanField(
                        default=False,
                        verbose_name="antes de Seguro Social, Medicare y desempleo/SINOT",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto de deducción",
                "verbose_name_plural": "conceptos de deducción",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConceptoIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.SlugField(max_length=30, unique=True, verbose_name="código"),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tributable_pr",
                    models.BooleanField(default=True, verbose_name="retención de PR"),
                ),
                (
                    "tributable_ss",
                    models.BooleanField(default=True, verbose_name="Seguro Social"),
                ),
                (
                    "tributable_medicare",
                    models.BooleanField(default=True, verbose_name="Medicare"),
                ),
                (
                    "tributable_futa",
                    models.BooleanField(default=True, verbose_name="FUTA"),
                ),
                (
                    "tributable_desempleo",
                    models.BooleanField(
                        default=True,
                        verbose_name="desempleo estatal (SUTA y aportación especial)",
                    ),
                ),
                (
                    "tributable_sinot",
                    models.BooleanField(default=True, verbose_name="SINOT"),
                ),
                (
                    "tributable_cfse",
                    models.BooleanField(default=True, verbose_name="nómina para CFSE"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("del_sistema", models.BooleanField(default=False, editable=False)),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto de ingreso",
                "verbose_name_plural": "conceptos de ingreso",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParametrosAnuales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "ss_tasa_empleado",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Seguro Social empleado %",
                    ),
                ),
                (
                    "ss_tasa_patrono",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Seguro Social patrono %",
                    ),
                ),
                (
                    "ss_tope",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tope salarial anual del Seguro Social ($)",
                    ),
                ),
                (
                    "medicare_tasa_empleado",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Medicare empleado %",
                    ),
                ),
                (
                    "medicare_tasa_patrono",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Medicare patrono %",
                    ),
                ),
                (
                    "medicare_adicional_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Medicare adicional (empleado) %",
                    ),
                ),
                (
                    "medicare_adicional_umbral",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="umbral anual del Medicare adicional ($)",
                    ),
                ),
                (
                    "futa_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="FUTA % (neto, después del crédito)",
                    ),
                ),
                (
                    "futa_tope",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tope salarial anual FUTA ($)",
                    ),
                ),
                (
                    "desempleo_tope",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Aplica a SUTA y a la aportación especial.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tope salarial anual de desempleo estatal ($)",
                    ),
                ),
                (
                    "sinot_tope",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tope salarial anual SINOT ($)",
                    ),
                ),
                (
                    "choferil_empleado_semanal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Seguro Choferil empleado por semana ($)",
                    ),
                ),
                (
                    "choferil_patrono_semanal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Seguro Choferil patrono por semana ($)",
                    ),
                ),
                (
                    "exencion_personal_individuo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención personal — individuo ($ anual)",
                    ),
                ),
                (
                    "exencion_personal_casado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención personal — casado ($ anual, completa)",
                    ),
                ),
                (
                    "exencion_dependiente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención por dependiente ($ anual)",
                    ),
                ),
                (
                    "exencion_dependiente_custodia",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención por dependiente con custodia compartida ($ anual)",
                    ),
                ),
                (
                    "exencion_veterano",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención de veterano ($ anual)",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "parámetros anuales",
                "verbose_name_plural": "parámetros anuales",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="SalarioMinimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "vigente_desde",
                    models.DateField(unique=True, verbose_name="vigente desde"),
                ),
                (
                    "tarifa_hora",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="salario mínimo por hora ($)",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "salario mínimo",
                "verbose_name_plural": "salarios mínimos",
                "ordering": ["-vigente_desde"],
            },
        ),
        migrations.CreateModel(
            name="TramoRetencionPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desde",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="desde ($)",
                    ),
                ),
                (
                    "hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="hasta ($)",
                    ),
                ),
                (
                    "cuota_fija",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cuota fija ($)",
                    ),
                ),
                (
                    "tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="tasa sobre el exceso %",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramos",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "tramo de retención",
                "ordering": ["desde"],
            },
        ),
        migrations.CreateModel(
            name="ReglaHorasExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("anterior", "Antes de Ley 4-2017"),
                            ("ley4", "Ley 4-2017"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "diario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="exceso de 8 horas diarias (×)",
                    ),
                ),
                (
                    "semanal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="exceso de 40 horas semanales (×)",
                    ),
                ),
                (
                    "septimo_dia",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="séptimo día / día de descanso (×)",
                    ),
                ),
                (
                    "periodo_alimentos",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="trabajo en el período de tomar alimentos (×)",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_horas_extra",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "ordering": ["regimen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parametros", "regimen"), name="regla_he_unica"
                    )
                ],
            },
        ),
    ]
