# Generated by Django 5.2.17 on 2026-09-29 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0002_valores_iniciales"),
    ]

    operations = [
        migrations.AddField(
            model_name="salariominimo",
            name="tarifa_propinas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Lo mínimo que el patrono paga en efectivo a meseros y otros empleados con propinas. Sus vacaciones y licencias por enfermedad se pagan al salario mínimo completo.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="mínimo en efectivo por hora para empleados con propinas ($)",
            ),
        ),
    ]
