# Generated by Django 5.2.17 on 2026-09-29 14:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0004_minimo_propinas_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosanuales",
            name="horas_por_dia",
            field=models.DecimalField(
                decimal_places=2,
                default=8,
                help_text="Para convertir días de licencia a horas.",
                max_digits=4,
                verbose_name="horas por día de licencia",
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="limite_patrono_pequeno_licencias",
            field=models.PositiveSmallIntegerField(
                default=12,
                verbose_name="patrono pequeño para licencias: hasta cuántos empleados",
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="tope_enfermedad_dias",
            field=models.DecimalField(
                decimal_places=2,
                default=15,
                max_digits=5,
                verbose_name="tope de licencia por enfermedad acumulada (días)",
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="tope_vacaciones_meses",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Ej.: 24 = hasta dos años de vacaciones acumuladas.",
                verbose_name="tope de vacaciones acumuladas (meses de acumulación)",
            ),
        ),
        migrations.CreateModel(
            name="ReglaLicencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vacaciones", "Vacaciones"),
                            ("enfermedad", "Enfermedad"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("anterior", "Antes de Ley 4-2017"),
                            ("ley4", "Ley 4-2017"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tamano",
                    models.CharField(
                        choices=[
                            ("grande", "Patrono de más empleados que el límite"),
                            ("pequeno", "Patrono pequeño (hasta el límite)"),
                        ],
                        max_length=10,
                        verbose_name="tamaño del patrono",
                    ),
                ),
                (
                    "anios_desde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="años de servicio desde",
                    ),
                ),
                (
                    "anios_hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = en adelante.",
                        max_digits=5,
                        null=True,
                        verbose_name="años de servicio hasta",
                    ),
                ),
                (
                    "horas_minimas_mes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="horas trabajadas mínimas en el mes",
                    ),
                ),
                (
                    "dias_por_mes",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="días acumulados por mes",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_licencia",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de licencia",
                "ordering": ["tipo", "regimen", "tamano", "anios_desde"],
            },
        ),
        migrations.CreateModel(
            name="ReglaBonoNavidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("anterior", "Antes de Ley 4-2017"),
                            ("ley4", "Ley 4-2017"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mes_inicio_periodo",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="10 = del 1 de octubre del año anterior al 30 de septiembre.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="mes en que empieza el período",
                    ),
                ),
                (
                    "horas_minimas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="horas mínimas trabajadas en el período",
                    ),
                ),
                (
                    "umbral_empleados",
                    models.PositiveSmallIntegerField(
                        verbose_name="patrono grande: más de cuántos empleados"
                    ),
                ),
                (
                    "porcentaje_grande",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% patrono grande",
                    ),
                ),
                (
                    "tope_grande",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bono máximo patrono grande ($)",
                    ),
                ),
                (
                    "porcentaje_pequeno",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% patrono pequeño",
                    ),
                ),
                (
                    "tope_pequeno",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bono máximo patrono pequeño ($)",
                    ),
                ),
                (
                    "tope_salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = sin tope de salario.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="salario máximo considerado ($)",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_bono",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla del bono de Navidad",
                "ordering": ["regimen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parametros", "regimen"), name="regla_bono_unica"
                    )
                ],
            },
        ),
    ]
