# Generated by Django 5.2.17 on 2026-09-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0006_reglas_licencias_bono_iniciales"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaMesada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("anterior", "Antes de Ley 4-2017"),
                            ("ley4", "Ley 4-2017"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "anios_desde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="años de servicio desde",
                    ),
                ),
                (
                    "anios_hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = en adelante.",
                        max_digits=5,
                        null=True,
                        verbose_name="años de servicio hasta",
                    ),
                ),
                (
                    "meses_sueldo",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="meses de sueldo"
                    ),
                ),
                (
                    "semanas_por_anio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="semanas por cada año de servicio",
                    ),
                ),
                (
                    "tope_meses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío = sin tope.",
                        max_digits=5,
                        null=True,
                        verbose_name="tope total (meses de sueldo)",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_mesada",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de mesada",
                "ordering": ["regimen", "anios_desde"],
            },
        ),
    ]
