# Generated by Django 5.2.17 on 2026-09-29 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0009_conceptos_liquidacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptoingreso",
            name="tributable_federal",
            field=models.BooleanField(
                default=True, verbose_name="retención federal (W-4)"
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="fed_ajuste_casado",
            field=models.DecimalField(
                decimal_places=2,
                default=12900,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="W-4 2020+: ajuste línea 1g, casado declarando conjuntamente ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="fed_ajuste_otro",
            field=models.DecimalField(
                decimal_places=2,
                default=8600,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="W-4 2020+: ajuste línea 1g, soltero o jefe de familia ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrosanuales",
            name="fed_valor_exencion",
            field=models.DecimalField(
                decimal_places=2,
                default=4300,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="W-4 2019 o anterior: valor de cada exención ($)",
            ),
        ),
        migrations.CreateModel(
            name="TramoRetencionFederal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("married", "Casado declarando conjuntamente"),
                            ("single", "Soltero o casado declarando por separado"),
                            ("head", "Jefe de familia"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tabla",
                    models.CharField(
                        choices=[("estandar", "Estándar"), ("paso2", "Paso 2 marcado")],
                        max_length=10,
                    ),
                ),
                (
                    "desde",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="desde ($)",
                    ),
                ),
                (
                    "cuota_fija",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cuota fija ($)",
                    ),
                ),
                (
                    "tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="tasa sobre el exceso %",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramos_federales",
                        to="parametros.parametrosanuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "tramo de retención federal",
                "ordering": ["estado_civil", "tabla", "desde"],
            },
        ),
    ]
