# Generated by Django 5.2.17 on 2026-09-29 19:12

from django.db import migrations, models


def _codigo_401k(apps, schema_editor):
    apps.get_model("parametros", "ConceptoDeduccion").objects.filter(codigo="retiro_401k").update(codigo_w2="D")


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0011_tablas_federales"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptodeduccion",
            name="codigo_w2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "D — 401(k), aportación electiva"),
                    ("E", "E — 403(b), aportación electiva"),
                    ("G", "G — 457(b), aportación electiva"),
                    ("S", "S — SIMPLE"),
                    ("AA", "AA — Roth 401(k)"),
                    ("BB", "BB — Roth 403(b)"),
                    ("W", "W — cuenta de ahorros de salud (HSA)"),
                    ("DD", "DD — costo de la cobertura de salud del patrono"),
                    ("C", "C — seguro de vida de grupo sobre $50,000"),
                ],
                help_text="Sólo para empleados con W-2 federal. Vacío = no va en la casilla 12.",
                max_length=2,
                verbose_name="código de la casilla 12 del W-2 federal",
            ),
        ),
        migrations.RunPython(_codigo_401k, migrations.RunPython.noop),
    ]
