# Generated by Django 5.2.17 on 2026-09-29 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0004_tasacfse"),
        ("empleados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonoNavidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("periodo_desde", models.DateField()),
                ("periodo_hasta", models.DateField()),
                ("regimen", models.CharField(max_length=10)),
                (
                    "numero_empleados",
                    models.PositiveIntegerField(verbose_name="empleados del patrono"),
                ),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="horas trabajadas en el período",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="salario del período",
                    ),
                ),
                ("elegible", models.BooleanField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("explicacion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("calculado", "Calculado"), ("pagado", "Pagado")],
                        default="calculado",
                        max_length=10,
                    ),
                ),
                ("parametros_verificados", models.BooleanField(default=False)),
                ("calculado_en", models.DateTimeField(auto_now=True)),
                (
                    "calculado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bonos_navidad",
                        to="companias.compania",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bonos_navidad",
                        to="empleados.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "bono de Navidad",
                "verbose_name_plural": "bonos de Navidad",
                "ordering": ["empleado__apellido_paterno", "empleado__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empleado", "anio"), name="un_bono_por_anio"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovimientoLicencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vacaciones", "Vacaciones"),
                            ("enfermedad", "Enfermedad"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clase",
                    models.CharField(
                        choices=[
                            ("saldo_inicial", "Saldo inicial"),
                            ("acumulacion", "Acumulación mensual"),
                            ("uso", "Uso (licencia disfrutada)"),
                            ("ajuste", "Ajuste"),
                            ("liquidacion", "Liquidación"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "periodo",
                    models.DateField(
                        blank=True,
                        help_text="Primer día del mes acumulado (solo acumulaciones).",
                        null=True,
                    ),
                ),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positivo suma, negativo resta.",
                        max_digits=8,
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_licencia",
                        to="empleados.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de licencia",
                "verbose_name_plural": "movimientos de licencia",
                "ordering": ["-fecha", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("clase", "acumulacion")),
                        fields=("empleado", "tipo", "periodo"),
                        name="una_acumulacion_por_mes",
                    )
                ],
            },
        ),
    ]
