# Generated by Django 5.2.17 on 2026-09-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0002_movimiento_periodo_nomina"),
        ("nomina", "0003_pagos_especiales"),
    ]

    operations = [
        migrations.AddField(
            model_name="bononavidad",
            name="periodo_nomina",
            field=models.ForeignKey(
                blank=True,
                help_text="Nómina especial en la que se paga.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bonos_navidad",
                to="nomina.periodonomina",
            ),
        ),
    ]
