# Generated by Django 5.2.17 on 2026-09-29 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0004_tasacfse"),
        ("empleados", "0001_initial"),
        ("parametros", "0008_reglas_mesada_iniciales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeduccionRecurrente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="monto por período",
                    ),
                ),
                ("desde", models.DateField(blank=True, null=True)),
                (
                    "hasta",
                    models.DateField(
                        blank=True, help_text="Vacío = sin fecha final.", null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.CharField(blank=True, max_length=200)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parametros.conceptodeduccion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deducciones_recurrentes",
                        to="empleados.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "deducción recurrente",
                "verbose_name_plural": "deducciones recurrentes",
                "ordering": ["concepto__nombre"],
            },
        ),
        migrations.CreateModel(
            name="EntradaNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incluir", models.BooleanField(default=True)),
                (
                    "horas_regulares",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas regulares",
                    ),
                ),
                (
                    "horas_extra_diarias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas extra (exceso de 8 diarias)",
                    ),
                ),
                (
                    "horas_extra_semanales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas extra (exceso de 40 semanales)",
                    ),
                ),
                (
                    "horas_septimo_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas en séptimo día",
                    ),
                ),
                (
                    "horas_periodo_alimentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas en período de alimentos",
                    ),
                ),
                (
                    "horas_vacaciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas de vacaciones",
                    ),
                ),
                (
                    "horas_enfermedad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="horas de enfermedad",
                    ),
                ),
                (
                    "semanas_choferil",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entradas_nomina",
                        to="empleados.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["empleado__apellido_paterno", "empleado__nombre"],
            },
        ),
        migrations.CreateModel(
            name="EntradaIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parametros.conceptoingreso",
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos",
                        to="nomina.entradanomina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntradaDeduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parametros.conceptodeduccion",
                    ),
                ),
                (
                    "recurrente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomina.deduccionrecurrente",
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deducciones",
                        to="nomina.entradanomina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("especial", "Especial (bono, ajuste, nómina final)"),
                            ("reverso", "Reverso"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="desde")),
                ("fecha_fin", models.DateField(verbose_name="hasta")),
                ("fecha_pago", models.DateField(verbose_name="fecha de pago")),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("calculada", "Pre-nómina calculada"),
                            ("cerrada", "Aprobada y cerrada"),
                            ("reversada", "Reversada"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("requiere_recalculo", models.BooleanField(default=True)),
                ("errores", models.JSONField(blank=True, default=list)),
                ("parametros_usados", models.JSONField(blank=True, default=dict)),
                ("motivo_reverso", models.CharField(blank=True, max_length=300)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("calculado_en", models.DateTimeField(blank=True, null=True)),
                ("cerrado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "calculado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periodos_nomina",
                        to="companias.compania",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverso_de",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverso",
                        to="nomina.periodonomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "período de nómina",
                "verbose_name_plural": "períodos de nómina",
                "ordering": ["-fecha_pago", "-id"],
            },
        ),
        migrations.AddField(
            model_name="entradanomina",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entradas",
                to="nomina.periodonomina",
            ),
        ),
        migrations.CreateModel(
            name="ResultadoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empleado_nombre", models.CharField(max_length=250)),
                ("numero_empleado", models.CharField(max_length=20)),
                ("ssn_ultimos4", models.CharField(max_length=4)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("regimen", models.CharField(max_length=10)),
                ("tarifa", models.DecimalField(decimal_places=4, max_digits=12)),
                ("tipo_pago", models.CharField(max_length=10)),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("bruto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_retenciones",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("neto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_patronal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("trib_pr", models.DecimalField(decimal_places=2, max_digits=12)),
                ("trib_ss", models.DecimalField(decimal_places=2, max_digits=12)),
                ("trib_medicare", models.DecimalField(decimal_places=2, max_digits=12)),
                ("trib_futa", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "trib_desempleo",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("trib_sinot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("trib_cfse", models.DecimalField(decimal_places=2, max_digits=12)),
                ("alertas", models.JSONField(blank=True, default=list)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_nomina",
                        to="empleados.empleado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="nomina.periodonomina",
                    ),
                ),
            ],
            options={
                "ordering": ["empleado_nombre"],
            },
        ),
        migrations.CreateModel(
            name="LineaResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso"),
                            ("retencion", "Retención"),
                            ("deduccion", "Deducción"),
                            ("patronal", "Aportación patronal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=150)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tasa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                ("explicacion", models.TextField(blank=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="nomina.resultadonomina",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="entradanomina",
            constraint=models.UniqueConstraint(
                fields=("periodo", "empleado"), name="una_entrada_por_empleado"
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadonomina",
            constraint=models.UniqueConstraint(
                fields=("periodo", "empleado"), name="un_resultado_por_empleado"
            ),
        ),
    ]
