# Generated by Django 5.2.17 on 2026-09-29 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0004_tasacfse"),
        ("nomina", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatoCheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("arriba", "Cheque arriba (voucher estándar)"),
                            ("medio", "Cheque en el medio"),
                            ("abajo", "Cheque abajo"),
                        ],
                        default="arriba",
                        max_length=10,
                        verbose_name="posición del cheque en la hoja",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "Inglés")],
                        default="es",
                        max_length=2,
                        verbose_name="monto en letras",
                    ),
                ),
                (
                    "siguiente_numero",
                    models.PositiveIntegerField(
                        default=1001,
                        help_text="Debe coincidir con el número preimpreso en la próxima hoja de cheques.",
                        verbose_name="próximo número de cheque",
                    ),
                ),
                (
                    "ajuste_horizontal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Positivo mueve la impresión a la derecha.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="ajuste horizontal (pulgadas)",
                    ),
                ),
                (
                    "ajuste_vertical",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Positivo mueve la impresión hacia abajo.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="ajuste vertical (pulgadas)",
                    ),
                ),
                (
                    "imprimir_encabezado",
                    models.BooleanField(
                        default=False,
                        help_text="Márquelo si su papel de cheque no los trae preimpresos.",
                        verbose_name="imprimir nombre de la compañía y número de cheque",
                    ),
                ),
                (
                    "nombre_cuenta",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="cuenta bancaria (se muestra en el talonario)",
                    ),
                ),
                (
                    "compania",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formato_cheque",
                        to="companias.compania",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="número")),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("beneficiario", models.CharField(max_length=250)),
                (
                    "estado",
                    models.CharField(
                        choices=[("emitido", "Emitido"), ("anulado", "Anulado")],
                        default="emitido",
                        max_length=10,
                    ),
                ),
                (
                    "motivo_anulacion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="motivo de anulación"
                    ),
                ),
                ("emitido_en", models.DateTimeField(auto_now_add=True)),
                ("anulado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheques_nomina",
                        to="companias.compania",
                    ),
                ),
                (
                    "emitido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheques",
                        to="nomina.periodonomina",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheques",
                        to="nomina.resultadonomina",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compania", "numero"), name="numero_cheque_unico"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "emitido")),
                        fields=("resultado",),
                        name="un_cheque_vigente_por_resultado",
                    ),
                ],
            },
        ),
    ]
