# Generated by Django 5.2.17 on 2026-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0002_cheques"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradanomina",
            name="horas_enfermedad_liquidadas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="entradanomina",
            name="horas_vacaciones_liquidadas",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
