# Generated by Django 5.2.17 on 2026-09-29 17:00

import apps.core.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0005_deposito_federal"),
        ("nomina", "0003_pagos_especiales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_efectiva", models.DateField()),
                ("depositos", models.PositiveIntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "huella",
                    models.CharField(max_length=64, verbose_name="SHA-256 del archivo"),
                ),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos_bancarios",
                        to="nomina.periodonomina",
                    ),
                ),
            ],
            options={
                "ordering": ["-generado_en"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionNACHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_banco",
                    models.CharField(
                        max_length=23, verbose_name="banco que recibe el archivo"
                    ),
                ),
                (
                    "ruta_banco",
                    models.CharField(
                        max_length=9, verbose_name="número de ruta del banco (ODFI)"
                    ),
                ),
                (
                    "origen_inmediato",
                    models.CharField(
                        help_text="Lo asigna el banco; a menudo es «1» seguido del EIN.",
                        max_length=10,
                        verbose_name="origen inmediato (Immediate Origin)",
                    ),
                ),
                (
                    "identificacion_compania",
                    models.CharField(
                        help_text="Lo asigna el banco; a menudo es «1» seguido del EIN.",
                        max_length=10,
                        verbose_name="identificación de la compañía (Company ID)",
                    ),
                ),
                (
                    "nombre_compania",
                    models.CharField(
                        max_length=16,
                        verbose_name="nombre de la compañía en el archivo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        default="NOMINA",
                        max_length=10,
                        verbose_name="descripción de la entrada",
                    ),
                ),
                (
                    "balanceado",
                    models.BooleanField(
                        default=False,
                        help_text="Algunos bancos piden un débito a la cuenta de la compañía por el total.",
                        verbose_name="archivo balanceado",
                    ),
                ),
                (
                    "ruta_compania",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        verbose_name="ruta de la cuenta de la compañía",
                    ),
                ),
                (
                    "cuenta_compania",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="cuenta de la compañía"
                    ),
                ),
                (
                    "cuenta_compania_ultimos4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "tipo_cuenta_compania",
                    models.CharField(
                        choices=[("cheques", "Cheques"), ("ahorros", "Ahorros")],
                        default="cheques",
                        max_length=10,
                        verbose_name="tipo de cuenta de la compañía",
                    ),
                ),
                (
                    "compania",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_nacha",
                        to="companias.compania",
                    ),
                ),
            ],
        ),
    ]
