# Generated by Django 5.2.17 on 2026-09-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0005_deposito_federal"),
        ("nomina", "0004_deposito_directo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=60)),
                (
                    "cuenta",
                    models.CharField(
                        max_length=150, verbose_name="cuenta en QuickBooks"
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_contables",
                        to="companias.compania",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compania", "clave"), name="cuenta_contable_unica"
                    )
                ],
            },
        ),
    ]
