# Generated by Django 5.2.17 on 2026-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0005_cuentas_contables"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadonomina",
            name="clasificacion_cfse",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="clasificación CFSE"
            ),
        ),
    ]
