# Generated by Django 5.2.17 on 2026-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0006_clasificacion_cfse"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadonomina",
            name="trib_federal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
