# Generated by Django 5.2.17 on 2026-09-29 12:32

import apps.core.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProveedorServicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="número de proveedor"),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[
                            ("individuo", "Individuo"),
                            ("entidad", "Entidad (corporación, sociedad, LLC)"),
                        ],
                        default="individuo",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="nombre o razón social"
                    ),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="segundo nombre"
                    ),
                ),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="apellido paterno"
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="apellido materno"
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre comercial"
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[("ssn", "SSN"), ("ein", "EIN")],
                        default="ssn",
                        max_length=3,
                        verbose_name="tipo de identificación",
                    ),
                ),
                (
                    "identificacion",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="número de identificación"
                    ),
                ),
                (
                    "identificacion_indice",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "identificacion_ultimos4",
                    models.CharField(editable=False, max_length=4),
                ),
                (
                    "direccion_linea1",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                (
                    "direccion_linea2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección (línea 2)"
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(default="PR", max_length=2)),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="código postal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "descripcion_servicio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="servicio que presta"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "relevo",
                    models.CharField(
                        choices=[
                            ("ninguno", "Sin relevo (retención completa)"),
                            ("parcial", "Relevo parcial"),
                            ("total", "Relevo total"),
                        ],
                        default="ninguno",
                        max_length=10,
                        verbose_name="relevo de retención",
                    ),
                ),
                (
                    "relevo_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solo para relevo parcial: el porcentaje que indica el certificado.",
                        max_digits=5,
                        null=True,
                        verbose_name="porcentaje de retención con relevo parcial (%)",
                    ),
                ),
                (
                    "relevo_vigente_hasta",
                    models.DateField(
                        blank=True, null=True, verbose_name="relevo vigente hasta"
                    ),
                ),
                (
                    "relevo_numero",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="número del certificado de relevo",
                    ),
                ),
                (
                    "deposito_directo",
                    models.BooleanField(default=False, verbose_name="depósito directo"),
                ),
                (
                    "banco_nombre",
                    models.CharField(blank=True, max_length=100, verbose_name="banco"),
                ),
                (
                    "banco_ruta",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="número de ruta"
                    ),
                ),
                (
                    "banco_cuenta",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="número de cuenta"
                    ),
                ),
                (
                    "banco_cuenta_ultimos4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "banco_tipo_cuenta",
                    models.CharField(
                        choices=[("cheques", "Cheques"), ("ahorros", "Ahorros")],
                        default="cheques",
                        max_length=10,
                        verbose_name="tipo de cuenta",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proveedores_servicios",
                        to="companias.compania",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "proveedor de servicios",
                "verbose_name_plural": "proveedores de servicios",
                "ordering": ["nombre", "apellido_paterno"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compania", "numero"), name="proveedor_numero_unico"
                    ),
                    models.UniqueConstraint(
                        fields=("compania", "identificacion_indice"),
                        name="proveedor_identificacion_unica",
                    ),
                ],
            },
        ),
    ]
