# Generated by Django 5.2.17 on 2026-09-29 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0002_initial"),
        ("servicios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedorservicios",
            name="relevo",
            field=models.CharField(
                choices=[
                    ("ninguno", "Sin relevo (retención completa)"),
                    ("parcial", "Relevo parcial"),
                    ("total", "Relevo total"),
                    (
                        "declaracion_jurada",
                        "Exento — Sección 1062.03(b) (declaración jurada)",
                    ),
                ],
                default="ninguno",
                max_length=20,
                verbose_name="relevo de retención",
            ),
        ),
        migrations.CreateModel(
            name="ConfigRetencionServicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "tasa_general",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="tasa de retención (%)",
                    ),
                ),
                (
                    "exencion_anual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Los primeros $ pagados en el año a cada proveedor no llevan retención.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="exención anual por proveedor ($)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificada", models.DateTimeField(auto_now=True)),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración de retención por servicios prestados",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="PagoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha del pago")),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        db_index=True, editable=False, verbose_name="año"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="factura / referencia"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("deposito", "Depósito directo"),
                            ("transferencia", "Transferencia / ACH"),
                            ("efectivo", "Efectivo"),
                            ("otro", "Otro"),
                        ],
                        default="cheque",
                        max_length=15,
                        verbose_name="método de pago",
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="número de cheque"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("manual", "Registro manual"),
                            ("importado", "Importado de Excel/CSV"),
                            ("nomina", "Ciclo de nómina"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto bruto"
                    ),
                ),
                (
                    "acumulado_previo",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "exencion_aplicada",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "base_sujeta",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="cantidad sujeta"
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="tasa aplicada (%)"
                    ),
                ),
                (
                    "tratamiento",
                    models.CharField(
                        choices=[
                            ("general", "Tasa general"),
                            ("relevo_parcial", "Relevo parcial"),
                            ("relevo_total", "Relevo total"),
                            (
                                "declaracion_jurada",
                                "Exento — Sección 1062.03(b) (declaración jurada)",
                            ),
                            ("exento_pago", "Pago exento (indicado por el usuario)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "retencion",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="retención"
                    ),
                ),
                (
                    "neto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="neto pagado"
                    ),
                ),
                ("explicacion", models.TextField()),
                (
                    "motivo_exencion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="motivo de la exención"
                    ),
                ),
                ("config_verificada", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[("registrado", "Registrado"), ("anulado", "Anulado")],
                        default="registrado",
                        max_length=12,
                    ),
                ),
                (
                    "motivo_anulacion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="motivo de la anulación",
                    ),
                ),
                ("anulado_en", models.DateTimeField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_servicios",
                        to="companias.compania",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="servicios.proveedorservicios",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago por servicios prestados",
                "verbose_name_plural": "pagos por servicios prestados",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["compania", "anio", "estado"],
                        name="servicios_p_compani_96114c_idx",
                    ),
                    models.Index(
                        fields=["proveedor", "anio"],
                        name="servicios_p_proveed_4c161d_idx",
                    ),
                ],
            },
        ),
    ]
