# Generated by Django 5.2.17 on 2026-09-29 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0003_compania_frecuencia_deposito"),
        ("servicios", "0003_config_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositoRetencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desde", models.DateField(verbose_name="pagos desde")),
                ("hasta", models.DateField(verbose_name="pagos hasta")),
                ("fecha_deposito", models.DateField(verbose_name="fecha del depósito")),
                (
                    "confirmacion",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="número de confirmación (SURI)",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto depositado"
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[("registrado", "Registrado"), ("anulado", "Anulado")],
                        default="registrado",
                        max_length=12,
                    ),
                ),
                ("motivo_anulacion", models.CharField(blank=True, max_length=200)),
                ("anulado_en", models.DateTimeField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depositos_retencion",
                        to="companias.compania",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "depósito de retención",
                "verbose_name_plural": "depósitos de retención",
                "ordering": ["-hasta", "-id"],
            },
        ),
        migrations.AddField(
            model_name="pagoservicio",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="servicios.depositoretencion",
            ),
        ),
    ]
