# Generated by Django 5.2.17 on 2026-09-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0005_cuentas_contables"),
        ("servicios", "0004_depositoretencion_pagoservicio_deposito"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoservicio",
            name="periodo_nomina",
            field=models.ForeignKey(
                blank=True,
                help_text="Ciclo de nómina en que se pagó.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_servicios",
                to="nomina.periodonomina",
            ),
        ),
    ]
