# Generated by Django 5.2.17 on 2026-09-29 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("usuario_nombre", models.CharField(blank=True, max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("login_fallido", "Intento de entrada fallido"),
                            ("logout", "Cierre de sesión"),
                            ("bloqueo", "Cuenta bloqueada"),
                            ("desbloqueo", "Cuenta desbloqueada"),
                            ("otp_configurado", "2FA configurado"),
                            ("otp_eliminado", "2FA eliminado"),
                            ("contrasena_cambiada", "Contraseña cambiada"),
                            (
                                "contrasena_restablecida",
                                "Contraseña restablecida por administrador",
                            ),
                            ("usuario_creado", "Usuario creado"),
                            ("usuario_modificado", "Usuario modificado"),
                            ("compania_creada", "Compañía creada"),
                            ("compania_modificada", "Compañía modificada"),
                            ("tasas_modificadas", "Tasas modificadas"),
                            ("catalogo_modificado", "Catálogo modificado"),
                            ("empleado_creado", "Empleado creado"),
                            ("empleado_modificado", "Empleado modificado"),
                            ("empleado_terminado", "Empleado terminado"),
                            ("empleados_importados", "Empleados importados"),
                            ("configuracion_modificada", "Configuración modificada"),
                            ("nomina_procesada", "Nómina procesada"),
                            ("nomina_reversada", "Nómina reversada"),
                            ("archivo_generado", "Archivo generado"),
                            ("acceso_denegado", "Acceso denegado"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "compania_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("compania_nombre", models.CharField(blank=True, max_length=200)),
                ("objeto_tipo", models.CharField(blank=True, max_length=100)),
                ("objeto_id", models.CharField(blank=True, max_length=64)),
                ("objeto_repr", models.CharField(blank=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("cambios", models.JSONField(blank=True, default=dict)),
                ("hash_anterior", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "bitácora de auditoría",
                "ordering": ["-id"],
            },
        ),
    ]
