# Generated by Django 5.2.17 on 2026-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0005_alter_registroauditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Intento de entrada fallido"),
                    ("logout", "Cierre de sesión"),
                    ("bloqueo", "Cuenta bloqueada"),
                    ("desbloqueo", "Cuenta desbloqueada"),
                    ("otp_configurado", "2FA configurado"),
                    ("otp_eliminado", "2FA eliminado"),
                    ("contrasena_cambiada", "Contraseña cambiada"),
                    (
                        "contrasena_restablecida",
                        "Contraseña restablecida por administrador",
                    ),
                    ("usuario_creado", "Usuario creado"),
                    ("usuario_modificado", "Usuario modificado"),
                    ("compania_creada", "Compañía creada"),
                    ("compania_modificada", "Compañía modificada"),
                    ("tasas_modificadas", "Tasas modificadas"),
                    ("catalogo_modificado", "Catálogo modificado"),
                    ("empleado_creado", "Empleado creado"),
                    ("empleado_modificado", "Empleado modificado"),
                    ("empleado_terminado", "Empleado terminado"),
                    ("empleados_importados", "Empleados importados"),
                    ("proveedor_creado", "Proveedor de servicios creado"),
                    ("proveedor_modificado", "Proveedor de servicios modificado"),
                    ("proveedores_importados", "Proveedores de servicios importados"),
                    ("pago_servicio_registrado", "Pago por servicios registrado"),
                    ("pago_servicio_anulado", "Pago por servicios anulado"),
                    ("pagos_importados", "Pagos por servicios importados"),
                    ("deposito_registrado", "Depósito de retención registrado"),
                    ("deposito_anulado", "Depósito de retención anulado"),
                    ("configuracion_modificada", "Configuración modificada"),
                    ("nomina_procesada", "Nómina procesada"),
                    ("nomina_reversada", "Nómina reversada"),
                    ("archivo_generado", "Archivo generado"),
                    ("acceso_denegado", "Acceso denegado"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
