# Generated by Django 5.2.17 on 2026-09-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0013_planillas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Intento de entrada fallido"),
                    ("logout", "Cierre de sesión"),
                    ("bloqueo", "Cuenta bloqueada"),
                    ("desbloqueo", "Cuenta desbloqueada"),
                    ("otp_configurado", "2FA configurado"),
                    ("otp_eliminado", "2FA eliminado"),
                    ("contrasena_cambiada", "Contraseña cambiada"),
                    (
                        "contrasena_restablecida",
                        "Contraseña restablecida por administrador",
                    ),
                    ("usuario_creado", "Usuario creado"),
                    ("usuario_modificado", "Usuario modificado"),
                    ("compania_creada", "Compañía creada"),
                    ("compania_modificada", "Compañía modificada"),
                    ("logo_compania", "Logo de la compañía modificado"),
                    ("planilla_radicada", "Radicación de planilla registrada"),
                    ("respaldo_creado", "Respaldo creado"),
                    ("respaldo_restaurado", "Base de datos restaurada de un respaldo"),
                    ("llaves_rotadas", "Llaves de cifrado rotadas"),
                    ("tasas_modificadas", "Tasas modificadas"),
                    ("catalogo_modificado", "Catálogo modificado"),
                    ("empleado_creado", "Empleado creado"),
                    ("empleado_modificado", "Empleado modificado"),
                    ("empleado_terminado", "Empleado terminado"),
                    ("empleados_importados", "Empleados importados"),
                    ("proveedor_creado", "Proveedor de servicios creado"),
                    ("proveedor_modificado", "Proveedor de servicios modificado"),
                    ("proveedores_importados", "Proveedores de servicios importados"),
                    ("pago_servicio_registrado", "Pago por servicios registrado"),
                    ("pago_servicio_anulado", "Pago por servicios anulado"),
                    ("pagos_importados", "Pagos por servicios importados"),
                    ("deposito_registrado", "Depósito de retención registrado"),
                    ("deposito_anulado", "Depósito de retención anulado"),
                    ("licencias_acumuladas", "Vacaciones/enfermedad acumuladas"),
                    ("licencia_movimiento", "Movimiento de vacaciones/enfermedad"),
                    ("bono_calculado", "Bono de Navidad calculado"),
                    ("periodo_creado", "Período de nómina creado"),
                    ("nomina_entradas", "Horas/ingresos de nómina modificados"),
                    ("nomina_calculada", "Pre-nómina calculada"),
                    ("deduccion_recurrente", "Deducción recurrente modificada"),
                    ("configuracion_modificada", "Configuración modificada"),
                    ("nomina_procesada", "Nómina procesada"),
                    ("nomina_reversada", "Nómina reversada"),
                    ("archivo_generado", "Archivo generado"),
                    ("cheque_emitido", "Cheques emitidos"),
                    ("cheque_anulado", "Cheque anulado"),
                    ("formato_cheque", "Formato de cheques modificado"),
                    ("config_nacha", "Datos bancarios de depósito directo modificados"),
                    ("cuentas_contables", "Cuentas contables modificadas"),
                    ("acceso_denegado", "Acceso denegado"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
