# Generated by Django 5.2.17 on 2026-09-29 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0006_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Radicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("trimestre", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fecha", models.DateField(verbose_name="fecha de radicación o pago")),
                (
                    "confirmacion",
                    models.CharField(
                        max_length=60, verbose_name="número de confirmación"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="monto pagado",
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=300)),
                ("registrado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radicaciones",
                        to="companias.compania",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "radicaciones",
                "ordering": ["-fecha", "-registrado_en"],
            },
        ),
    ]
