# Generated by Django 5.2.17 on 2026-09-29 12:15

import apps.core.campos
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="nombre legal"),
                ),
                ("nombre_comercial", models.CharField(blank=True, max_length=200)),
                (
                    "industria",
                    models.CharField(
                        choices=[
                            ("restaurante", "Restaurante"),
                            ("farmacia", "Farmacia"),
                            ("construccion", "Construcción"),
                            ("salud", "Salud"),
                            ("retail", "Comercio al detal"),
                            ("servicios", "Servicios"),
                            ("otra", "Otra"),
                        ],
                        default="otra",
                        max_length=20,
                    ),
                ),
                (
                    "ein",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="EIN"
                    ),
                ),
                (
                    "ein_indice",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ein_ultimos4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "registro_comerciante",
                    apps.core.campos.CampoCifrado(
                        blank=True,
                        null=True,
                        verbose_name="número de registro de comerciante (Hacienda)",
                    ),
                ),
                (
                    "cuenta_patronal_dtrh",
                    apps.core.campos.CampoCifrado(
                        blank=True,
                        help_text="Número de cuenta patronal de desempleo e incapacidad.",
                        null=True,
                        verbose_name="cuenta patronal DTRH",
                    ),
                ),
                (
                    "poliza_cfse",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="número de póliza CFSE"
                    ),
                ),
                (
                    "direccion_linea1",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                (
                    "direccion_linea2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección (línea 2)"
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(default="PR", max_length=2)),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="código postal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                ("persona_contacto", models.CharField(blank=True, max_length=150)),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email de contacto"
                    ),
                ),
                (
                    "frecuencia_pago",
                    models.CharField(
                        choices=[
                            ("semanal", "Semanal"),
                            ("bisemanal", "Bisemanal (cada 2 semanas)"),
                            ("quincenal", "Quincenal (2 veces al mes)"),
                            ("mensual", "Mensual"),
                        ],
                        default="semanal",
                        max_length=20,
                        verbose_name="frecuencia de pago",
                    ),
                ),
                (
                    "numero_empleados",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Se usa para las reglas que dependen del tamaño del patrono (vacaciones, enfermedad, bono de Navidad).",
                        verbose_name="número de empleados (declarado)",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("modificada", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "compañía",
                "verbose_name_plural": "compañías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClasificacionCFSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="código")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clasificaciones_cfse",
                        to="companias.compania",
                    ),
                ),
            ],
            options={
                "verbose_name": "clasificación CFSE",
                "verbose_name_plural": "clasificaciones CFSE",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, verbose_name="código"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departamentos",
                        to="companias.compania",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TasasCompania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "suta_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="desempleo estatal (SUTA) %",
                    ),
                ),
                (
                    "aportacion_especial_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="aportación especial %",
                    ),
                ),
                (
                    "sinot_empleado_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="incapacidad (SINOT) empleado %",
                    ),
                ),
                (
                    "sinot_patrono_tasa",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="incapacidad (SINOT) patrono %",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("modificada", models.DateTimeField(auto_now=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasas",
                        to="companias.compania",
                    ),
                ),
            ],
            options={
                "verbose_name": "tasas de la compañía",
                "verbose_name_plural": "tasas de la compañía",
                "ordering": ["-anio"],
            },
        ),
    ]
