# Generated by Django 5.2.17 on 2026-09-29 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasascompania",
            name="verificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="clasificacioncfse",
            constraint=models.UniqueConstraint(
                fields=("compania", "codigo"), name="clasificacion_cfse_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="departamento",
            constraint=models.UniqueConstraint(
                fields=("compania", "nombre"), name="departamento_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasascompania",
            constraint=models.UniqueConstraint(
                fields=("compania", "anio"), name="tasas_unicas_por_anio"
            ),
        ),
    ]
