# Generated by Django 5.2.17 on 2026-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compania",
            name="frecuencia_deposito",
            field=models.CharField(
                choices=[("mensual", "Mensual"), ("bisemanal", "Bisemanal")],
                default="mensual",
                help_text="Cada cuánto se depositan las retenciones (nómina y servicios prestados).",
                max_length=10,
                verbose_name="frecuencia de depósito de retenciones (Hacienda)",
            ),
        ),
    ]
