# Generated by Django 5.2.17 on 2026-09-29 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0003_compania_frecuencia_deposito"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasaCFSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                (
                    "tasa_por_100",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="tasa por cada $100 de nómina",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_verificar", "POR VERIFICAR"),
                            ("verificado", "Verificado"),
                        ],
                        default="por_verificar",
                        max_length=20,
                    ),
                ),
                ("modificada", models.DateTimeField(auto_now=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasas",
                        to="companias.clasificacioncfse",
                    ),
                ),
            ],
            options={
                "verbose_name": "tasa CFSE",
                "verbose_name_plural": "tasas CFSE",
                "ordering": ["-anio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clasificacion", "anio"), name="tasa_cfse_unica"
                    )
                ],
            },
        ),
    ]
