# Generated by Django 5.2.17 on 2026-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companias", "0004_tasacfse"),
    ]

    operations = [
        migrations.AddField(
            model_name="compania",
            name="frecuencia_deposito_federal",
            field=models.CharField(
                choices=[("mensual", "Mensual"), ("bisemanal", "Bisemanal")],
                default="mensual",
                help_text="Según el período de referencia del IRS (lookback): mensual o bisemanal (semiweekly).",
                max_length=10,
                verbose_name="frecuencia de depósito federal (941)",
            ),
        ),
    ]
