# Generated by Django 5.2.17 on 2026-09-29 12:15

import apps.core.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_empleado",
                    models.CharField(max_length=20, verbose_name="número de empleado"),
                ),
                ("nombre", models.CharField(max_length=60)),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="segundo nombre"
                    ),
                ),
                (
                    "apellido_paterno",
                    models.CharField(max_length=60, verbose_name="apellido paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="apellido materno"
                    ),
                ),
                (
                    "ssn",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="SSN"
                    ),
                ),
                (
                    "ssn_indice",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("ssn_ultimos4", models.CharField(editable=False, max_length=4)),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "direccion_linea1",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                (
                    "direccion_linea2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección (línea 2)"
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(default="PR", max_length=2)),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="código postal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha_empleo", models.DateField(verbose_name="fecha de empleo")),
                (
                    "regimen_laboral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anterior", "Antes de Ley 4-2017"),
                            ("ley4", "Ley 4-2017"),
                        ],
                        help_text="En blanco = automático según la fecha de empleo (antes o después del 26-ene-2017).",
                        max_length=10,
                        verbose_name="régimen laboral",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("hora", "Por hora"),
                            ("salario", "Salario fijo (no exento)"),
                            ("exento", "Salario fijo — exento (sin horas extra)"),
                        ],
                        default="hora",
                        max_length=10,
                        verbose_name="tipo de pago",
                    ),
                ),
                (
                    "tarifa",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Por hora: tarifa por hora. Salario: cantidad por período de pago.",
                        max_digits=12,
                    ),
                ),
                (
                    "horas_regulares_periodo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para empleados asalariados: horas que cubre el salario (para calcular la tarifa por hora).",
                        max_digits=6,
                        null=True,
                        verbose_name="horas regulares por período",
                    ),
                ),
                (
                    "aplica_choferil",
                    models.BooleanField(
                        default=False, verbose_name="aplica Seguro Choferil"
                    ),
                ),
                ("recibe_propinas", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_terminacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de terminación"
                    ),
                ),
                (
                    "razon_terminacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("renuncia", "Renuncia"),
                            ("despido", "Despido"),
                            ("cesantia", "Cesantía / reducción de personal"),
                            ("fin_contrato", "Fin de contrato"),
                            ("jubilacion", "Jubilación"),
                            ("fallecimiento", "Fallecimiento"),
                            ("otra", "Otra"),
                        ],
                        max_length=20,
                        verbose_name="razón de terminación",
                    ),
                ),
                (
                    "r4_estado_civil",
                    models.CharField(
                        choices=[
                            ("soltero", "Soltero(a)"),
                            ("casado", "Casado(a)"),
                            ("casado_separado", "Casado(a) — planilla separada"),
                            ("jefe_familia", "Jefe(a) de familia"),
                        ],
                        default="soltero",
                        max_length=20,
                        verbose_name="estado civil (499 R-4)",
                    ),
                ),
                (
                    "r4_exencion_personal",
                    models.CharField(
                        choices=[
                            ("completa", "Completa"),
                            ("mitad", "Mitad"),
                            ("ninguna", "Ninguna"),
                        ],
                        default="completa",
                        max_length=10,
                        verbose_name="exención personal (499 R-4)",
                    ),
                ),
                (
                    "r4_dependientes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="dependientes"
                    ),
                ),
                (
                    "r4_dependientes_custodia_compartida",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="dependientes (custodia compartida)"
                    ),
                ),
                (
                    "r4_veterano",
                    models.BooleanField(
                        default=False, verbose_name="exención de veterano"
                    ),
                ),
                (
                    "r4_concesion_deducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="concesión por deducciones ($ anual)",
                    ),
                ),
                (
                    "r4_retencion_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="retención adicional por período ($)",
                    ),
                ),
                (
                    "w4_aplica",
                    models.BooleanField(
                        default=False, verbose_name="aplica retención federal (W-4)"
                    ),
                ),
                (
                    "w4_estado_civil",
                    models.CharField(
                        choices=[
                            ("single", "Soltero o casado declarando por separado"),
                            ("married", "Casado declarando conjuntamente"),
                            ("head", "Jefe de familia"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="estado civil (W-4)",
                    ),
                ),
                (
                    "w4_paso2",
                    models.BooleanField(
                        default=False,
                        verbose_name="W-4 paso 2 marcado (múltiples empleos)",
                    ),
                ),
                (
                    "w4_dependientes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="W-4 paso 3: dependientes ($)",
                    ),
                ),
                (
                    "w4_otros_ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="W-4 paso 4(a): otros ingresos ($)",
                    ),
                ),
                (
                    "w4_deducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="W-4 paso 4(b): deducciones ($)",
                    ),
                ),
                (
                    "w4_retencion_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="W-4 paso 4(c): retención adicional ($)",
                    ),
                ),
                (
                    "deposito_directo",
                    models.BooleanField(default=False, verbose_name="depósito directo"),
                ),
                (
                    "banco_nombre",
                    models.CharField(blank=True, max_length=100, verbose_name="banco"),
                ),
                (
                    "banco_ruta",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="número de ruta"
                    ),
                ),
                (
                    "banco_cuenta",
                    apps.core.campos.CampoCifrado(
                        blank=True, null=True, verbose_name="número de cuenta"
                    ),
                ),
                (
                    "banco_cuenta_ultimos4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "banco_tipo_cuenta",
                    models.CharField(
                        choices=[("cheques", "Cheques"), ("ahorros", "Ahorros")],
                        default="cheques",
                        max_length=10,
                        verbose_name="tipo de cuenta",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "clasificacion_cfse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companias.clasificacioncfse",
                        verbose_name="clasificación CFSE",
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="companias.compania",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companias.departamento",
                    ),
                ),
            ],
            options={
                "ordering": ["apellido_paterno", "apellido_materno", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["compania", "activo"],
                        name="empleados_e_compani_0a6cd5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compania", "numero_empleado"),
                        name="empleado_numero_unico",
                    ),
                    models.UniqueConstraint(
                        fields=("compania", "ssn_indice"), name="empleado_ssn_unico"
                    ),
                ],
            },
        ),
    ]
