# Generated by Django 5.2.17 on 2026-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="w4_exenciones",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="W-4 2019 o anterior: exenciones (allowances)"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="w4_version",
            field=models.CharField(
                choices=[("2020", "2020 o posterior"), ("2019", "2019 o anterior")],
                default="2020",
                max_length=4,
                verbose_name="versión del W-4",
            ),
        ),
    ]
